---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qtube
spec:
  ingressClassName: nginx
  rules:
  - host: qtube.show.hienph.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: qtube
            port:
              number: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: qtube
spec:
  selector:
    app: qtube
  type: ClusterIP
  ports:
  - name: qtube
    protocol: TCP
    port: 8000
    targetPort: 8000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  qtube
  labels:
    app:  qtube
spec:
  selector:
    matchLabels:
      app: qtube
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  qtube
    spec:
      containers:
      - name:  qtube
        image: ghcr.io/hienduyph/qtube:main
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        readinessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        ports:
        - containerPort: 8000
          name:  qtube
      restartPolicy: Always
