apiVersion: apps/v1
kind: Deployment
metadata:
  name:  qtube
  labels:
    app:  qtube
spec:
  selector:
    matchLabels:
      app: qtube
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  qtube
    spec:
      containers:
      - name:  qtube
        image:  ghcr.io/hienduyph/qtube:main
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        ports:
        - containerPort: 8080
          name:  qtube
      restartPolicy: Always
